version: '3.8'

services:
  api-gateway:
    image: ${ECR_REGISTRY}/freedmai-api-gateway:latest
    container_name: freedmai-api-gateway-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - config/prod.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - freedmai-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  api-gateway-new:
    image: ${ECR_REGISTRY}/freedmai-api-gateway:latest
    container_name: freedmai-api-gateway-new
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - config/prod.env
    volumes:
      - ./logs:/app/logs
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - freedmai-network
    profiles:
      - deployment

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - freedmai-network

networks:
  freedmai-network:
    driver: bridge
